language: ruby

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - graphicsmagick

before_install:
  - bash install/libvips.sh
  - bash install/imagemagick.sh

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby-9.2.0.0

# Doesn't currently work with MRI 2.5.1: https://github.com/travis-ci/travis-ci/issues/8978
# cache: bundler

script:
  - bundle exec rake test
  - bundle exec rake test TEST=test/mini_magick_test.rb GM=1
