language: ruby

sudo: required

rvm:
  - "2.0"
  - "2.1.10"
  - "2.2.7"
  - "2.3.4"
  - "2.4.1"
  - "jruby-9.0.4.0"

script: rake test

cache: bundler
cache: apt

before_install:
  - echo "Installing libvips..."
  - sudo add-apt-repository -y ppa:lovell/precise-backport-vips
  - sudo apt-get update
  - sudo apt-get install -y libvips-dev
  - echo "Completed libvips installation."

addons:
  apt:
    packages:
      - imagemagick
      - libmagickcore-dev
      - libmagickwand-dev
      - graphicsmagick
