language: ruby

sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev
  - sudo apt-get install -qq graphicsmagick

rvm:
  - "2.0"
  - "2.1.10"
  - "2.2.7"
  - "2.3.4"
  - "2.4.1"
  - "jruby-9.0.4.0"

script: rake test

cache: bundler
