sudo: false

addons:
  apt:
    packages:
      # libvips
      - gobject-introspection
      - libglib2.0-dev
      - libgirepository1.0-dev
      - libpoppler-glib-dev
      - libvips-tools

cache:
  directories:
    - $HOME/libvips
    - $HOME/ImageMagick

before_install:
  - bash install/libvips.sh --without-python
  - bash install/imagemagick.sh
  - vips --version
  - magick --version

language: ruby

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby-9.1.16.0

# Doesn't currently work with MRI 2.5.1: https://github.com/travis-ci/travis-ci/issues/8978
# cache: bundler

script: bundle exec rake test
