language: ruby

sudo: false

rvm:
  - "2.1"
  - "2.2"
  - "jruby-9.0.4.0"
  - "rbx-2.5.8"

cache: bundler

addons:
  apt:
    packages:
      - imagemagick
      - libmagickcore-dev
      - libmagickwand-dev
      - graphicsmagick
