language: ruby

sudo: required
dist: trusty

before_install:
  - bash install/libvips.sh
  - bash install/imagemagick.sh

rvm:
  - "2.2"
  - "2.3"
  - "2.4"
  - "2.5"
  - "jruby-9.1.16.0"

script: rake test

cache: bundler
