language: ruby

sudo: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - VIPS_VERSION_MAJOR=8
    - VIPS_VERSION_MINOR=5
    - VIPS_VERSION_MICRO=7
    - PATH=$HOME/vips/bin:$PATH
    - LD_LIBRARY_PATH=$HOME/vips/lib:$LD_LIBRARY_PATH
    - PKG_CONFIG_PATH=$HOME/vips/lib/pkgconfig:$PKG_CONFIG_PATH

rvm:
  - "2.0"
  - "2.1.10"
  - "2.2.7"
  - "2.3.4"
  - "2.4.1"
  - "jruby-9.0.4.0"

script: rake test

cache:
  bundler: true
  directories:
    - $HOME/vips

before_install:
  - uname -a
  - bash install-vips.sh --without-python

addons:
  apt:
    packages:
      - imagemagick
      - libmagickcore-dev
      - libmagickwand-dev
      - graphicsmagick
      - libexpat1-dev
      - gettext
      - liblcms2-dev
      - libmagickwand-dev
      - libopenexr-dev
      - libcfitsio3-dev
      - libgif-dev
      - libgs-dev
      - libgsf-1-dev
      - libmatio-dev
      - libopenslide-dev
      - liborc-0.4-dev
      - libpango1.0-dev
      - libpoppler-glib-dev
      - librsvg2-dev
      - libwebp-dev
        # missing on trusty, unfortunately
        # - libwebpmux2
      - libfftw3-dev
      - libglib2.0-dev
