language: ruby

sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev
  - sudo apt-get install -qq graphicsmagick

rvm:
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
  - "jruby-9.1.9.0"

script: rake test

cache: bundler
